language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cherdt/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cherdt/udemy-docker-react npm run test -- --coverage


